# Generated by Django 5.2.1 on 2025-05-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dds_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(
                choices=[("Бизнес", "бизнес"), ("Личное", "личное"), ("Налог", "налог")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="name",
            field=models.CharField(choices=[("Пополнение", "пополнение"), ("Списание", "списание")], max_length=10),
        ),
    ]
