# Generated by Django 5.2.1 on 2025-05-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dds_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="record",
            options={"verbose_name": "Запись", "verbose_name_plural": "Записи"},
        ),
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name": "Статус", "verbose_name_plural": "Статусы"},
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={"verbose_name": "Подкатегория", "verbose_name_plural": "Подкатегории"},
        ),
        migrations.AlterModelOptions(
            name="type",
            options={"verbose_name": "Тип", "verbose_name_plural": "Типы"},
        ),
    ]
